Mj devs pr
BDonnot/Grid2Op pull request #122
Opened 2021-01-07 11:24 UTC by mjothy

Added EpisodeData to return API of runs in runner.
This required some changes to EpisodeData class, which was only storing in memory some data if the disk serialisation flag was on. I added a new flag for this in memory storing to keep it optional since it can take a lot of space.
Previous behavior is still available through old API, I just added a new method 'run_detailed' that enables the additional data.

2021-01-07 13:46 UTC, BDonnot requested changes
Il faut, à mon avis (désolé j'ai changé depuis la dernière fois) modifié l'implémentation du runner (en changeant la signature en fonction de  la variable `force_detail` qu'on pourrait renommer sans doute `add_detailed_output` par exemple.

Aussi, il faut absolument faire des tests :-)
Et préciser dans la doc que le retour de la fonction `run` est modifié selon la valeur de l'argument `add_detailed_output`

2021-01-07 13:46 UTC, BDonnot commented on grid2op/Runner/Runner.py
A la réflexion, faire deux fonctions comme ça c'est pas tip top :-/

Vu ce qui est fait, je ferais une seule fonction (`runner.run`) avec l'argument par défaut  "force_detail=False"
et je fowarderais dans les fonctions "en dessous" (_run_parrallel, _run_one_process_parrallel, etc.).

Si "force_detail" vaut false dans les fonctions "en dessous" on oblige à ne pas ajouter le "EpisodeData" dans ce qui est renvoyé.

2021-01-07 14:09 UTC, mjothy commented on grid2op/Runner/Runner.py
Hello, je pourrais faire ça oui, mais vu la structure du retour, je suis pas sûr que ça soit une bonne idée, ça voudrait dire qu'un flag provoque un nombre d'item dans l'array différent, et pourrait causer des confusions sur le parsing du retour.
Quand on avait regardé, tu avais dit que tu avais prévu de faire un refactor de cette classe, et notamment utiliser une classe pour tenir un résultat de run par scénario. Il me semble plus logique d'attendre ce refactor pour changer l'API non ?

Pour les tests, c'est quoi la procédure ? Quels tests veux tu, et comment puis-je les implémenter/lancer/valider ?

2021-01-07 14:50 UTC, BDonnot commented on grid2op/Runner/Runner.py
Pour les tests, il faut inclure des tests unitaires pour vérifier que cette nouvelle fonctionnalité fonctionne prévu, et surtout, si jamais on la modifie plus tard, pour vérifier que le nouveau comportement reproduit bien l'ancien.
Les tests sont  à coder, pour ce fichier, dans le fichier `test_Runner.py` du dossier `grid2op/tests`.

Pour le refacto, oui j'ai conscience d'avoir changé d'avis, ce qui n'est pas tip top. Mais voir les deux fonctions c'est vraiment pas top.

Je pense garder l'API run, et retourner une liste de taille de différente selon les arguments n'est pas non plus si terrible que ça. Je préférerais donc qu'il n'y ait pas de duplicité et avoir un comportement différent selon l'argument, si c'est possible.

2021-01-07 14:59 UTC, mjothy commented on grid2op/Runner/Runner.py
Ok ! Je m'occupe de ça.

2021-01-07 15:06 UTC, BDonnot commented on grid2op/Runner/Runner.py
Merci :-)

2021-01-08 14:37 UTC, mjothy commented
Added tests, and changed the API to be 1 function with additional flag per Bdonnot's request.

2021-01-11 16:10 UTC, BDonnot requested changes
Il y a 2-3 trucs cosmétiques à modifier, mais aussi, pour que les tests passent (cf discord) mettre:
```python
        # otherwise on windows it sometimes fail in the runner in multi process
        self.init_env()
        self.env = None
   ```
dans le "grid2op\Runner\Runner.py" aux liggnes 539 et suivantes.

Chez moi ça corrige le test que ni passe pas, même si la solution, sur le long terme, n'est pas satisfaisante je pense.

2021-01-11 16:10 UTC, BDonnot commented on grid2op/Runner/Runner.py
> +                                   info, detailed_output)
force_detail is not used in `episode.incr_store`

2021-01-11 16:10 UTC, BDonnot commented on grid2op/tests/test_Runner.py
> +        np.testing.assert_almost_equal(episode_data.rewards, self.all_real_rewards, 5)
Est-ce que, par cohérence avec le reste, tu peux reprendre la syntaxe  `assert np.abs(cum_reward - self.real_reward) <= self.tol_one` ou quelque chose du genre ?
Merci

2021-01-11 16:10 UTC, BDonnot commented on grid2op/tests/test_Runner.py
> +            np.testing.assert_almost_equal(episode_data.rewards, self.all_real_rewards, 5)
Pareil qu'au dessus, ça serait plus cohérent (avec les autres tests) avec quelque chose comme `assert np.abs(cum_reward - self.real_reward) <= self.tol_one`

2021-01-13 14:49 UTC, BDonnot reviewed
Ok i think it's good now :-)
Thanks

2021-01-13 14:50 UTC, BDonnot approved these changes
Everything looks good, thanks

2021-01-13 14:51 UTC, merged