Update notebooks
BDonnot/Grid2Op pull request #39
Opened 2020-05-11 20:38 UTC by Ashargin

2020-05-18 13:14 UTC, BDonnot requested changes

2020-05-18 13:14 UTC, BDonnot commented on getting_started/2_Action_GridManipulation.ipynb
> +    "* [`action_space.set_bus`](../documentation/html/action.html#grid2op.Action.HelperAction.set_bus) ($\\leftarrow$ this is a link)\n",
Non il faut garder la doc sur internet maintenant !

2020-05-18 13:14 UTC, BDonnot commented on getting_started/2_Action_GridManipulation.ipynb
> +    "For a detailed list of ambiguous actions, the documentation is the **only** official source. Only some examples are presented here. The documentation is available at [\\_check\\_for\\_ambiguity]
doc sur internet, pas doc en local.

2020-05-18 13:14 UTC, BDonnot commented on getting_started/2_Action_GridManipulation.ipynb
> +    "As opposed to the previous plateform, [pypownet](https://github.com/MarvinLer/pypownet), there are no restrictions on actions in Grid2Op. Generally speaking, an Action can modify production, loa
doc sur internet pas en local

2020-05-18 13:14 UTC, BDonnot commented on getting_started/1_Observation_Agents.ipynb
> +    "obs.prod_p"
je ne vois le notebook que avec la vue github donc vraiment pas top, mais es tu sur qu'il ne s'agit pas d'une observation venant d'un "simualte" ici ? Si c'est le cas, pour éviter les ambiguité, il faut garder obs_sim :-)

2020-05-18 13:35 UTC, Ashargin commented on getting_started/2_Action_GridManipulation.ipynb
> +    "For a detailed list of ambiguous actions, the documentation is the **only** official source. Only some examples are presented here. The documentation is available at [\\_check\\_for\\_ambiguity]
done

2020-05-18 13:41 UTC, Ashargin commented on getting_started/2_Action_GridManipulation.ipynb
> +    "* [`action_space.set_bus`](../documentation/html/action.html#grid2op.Action.HelperAction.set_bus) ($\\leftarrow$ this is a link)\n",
done

2020-05-18 13:42 UTC, Ashargin commented on getting_started/2_Action_GridManipulation.ipynb
> +    "As opposed to the previous plateform, [pypownet](https://github.com/MarvinLer/pypownet), there are no restrictions on actions in Grid2Op. Generally speaking, an Action can modify production, loa
done

2020-05-18 13:43 UTC, Ashargin commented on getting_started/1_Observation_Agents.ipynb
> +    "obs.prod_p"
Je suis sûr, là j'affiche obs.prod_p, et juste ensuite obs_sim.prod_p :)

2020-05-19 07:38 UTC, BDonnot commented
C'est normal qu'il reste un TODO dans le notebook 7 ? Je ne peux pas le merger s'il reste des todo dedans ;-)

2020-05-19 13:20 UTC, BDonnot approved these changes

2020-05-19 13:22 UTC, merged