MultimixEnv: Add forward to all envs for chunk_size and chronics tell_id
BDonnot/Grid2Op pull request #87
Opened 2020-07-01 13:50 UTC by Tezirg

2020-07-01 16:44 UTC, BDonnot requested changes
The name of the environment could maybe be improved and really dependant on the underlying powergrid. Otherwise we will get trouble if we release different "multimix" environments.

2020-07-01 16:44 UTC, BDonnot commented on grid2op/Environment/MultiMixEnv.py
> +        tmp_env.env_name = "multimix"
Nope ça ne va pas ça. Sinon si tu as deux multimix avec des réseaux électrique sous jacent différent ça va planter sévère.
Il faut que le nom de l'environment soit "unique" ou disons que si deux environment ont le même nom, alors le réseau électrique sous jacent soit le même. Il faudrait donc récuperer le env name quelques part.

2020-07-02 07:45 UTC, Tezirg commented on grid2op/Environment/MultiMixEnv.py
> +        tmp_env.env_name = "multimix"
True, mis a jour avec le basename du dataset directory

2020-07-02 07:47 UTC, BDonnot approved these changes

2020-07-02 07:51 UTC, merged