Marota random redispatch agent
BDonnot/Grid2Op pull request #96
Opened 2020-07-15 16:11 UTC by Tezirg

2020-07-17 16:38 UTC, BDonnot commented
I think this agent already exist. 
If you use the IdToVect converter and authorize only the redispatching, and call the "sample" method, this is exactly what it will do.

Or am I missing something ?

2020-07-17 16:46 UTC, BDonnot requested changes
I don't know to what problem this class could solve better than the "IdToAct" class if you restrict it to only redispatching action (and maybe use filtering for the nb_max_generator is it's really needed).

The name is also completely misleading. It is not an Agent that takes at random uniformely amongs all possible redispatching actions. It takes some pre specified redispatching action at random...

However i found a clear setting in the case IdToAct does a much much better job (it always respects the ramps).
I you want to improve it by giving the number of "splits" you do for redispatch (instead of 7 both side, you can do 1 or 2 or 42)

I'm not found of the current implementation for these reasons.

2020-07-17 16:46 UTC, BDonnot commented on grid2op/Agent/RandomRedispatchAgent.py
> +        gens_redisp = gens_ids[self.action_space.gen_redispatchable == True]
remove the "== True"
`gens_redisp = gens_ids[self.action_space.gen_redispatchable]`
evaluates faster and is more readable

2020-07-20 09:13 UTC, marota commented
Le besoin est d'avoir un agent sur lequel on puisse faire des tests pour le redispatching facilement. 
Je n'ai pas vu ce type d'agent dans la liste des agents. Cet agent avait été revu avec Jean.
Si vous voyez comment faire différemment ou l'améliorer pas de soucis pour le changer

2020-07-20 11:51 UTC, BDonnot commented
If this is for testing purpose I suggest we had a dedicated "test" or "testing" submodule to grid2op and put it there. Otherwise people will legitimately ask question about it trying to use it.
Beside, there are plenty of tests for redispatching already.

2020-07-29 17:04 UTC, BDonnot commented
Will be added in the other PR (PR #97)

2020-07-29 17:04 UTC, closed without merging